# Generated by Django 3.2.8 on 2021-10-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postuser',
            name='api_token',
            field=models.CharField(db_index=True, max_length=32, null=True, unique=True, verbose_name='Account api token'),
        ),
    ]
